name: dictionary
description: A comprehensive Myanmar online dictionary

# Remove this line to publish to pub.dev
publish_to: 'none'

version: 1.0.3+39

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Local lidea package, development only
  lidea:
    path: ../lidea
    # git:
    #   url: git://github.com/laisiangtho/lidea.git
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Add assets
  assets:
    - assets/env.json
    - assets/word.db
    - assets/sense.db
    - assets/thesaurus.db

  # fonts from lidea
  fonts:
    - family: Lato
      fonts:
        - asset: packages/lidea/fonts/Lato-Regular.ttf
        - asset: packages/lidea/fonts/Lato-Thin.ttf
        - asset: packages/lidea/fonts/Lato-Light.ttf
        - asset: packages/lidea/fonts/Lato-Bold.ttf

    - family: Lidea
      fonts:
        - asset: packages/lidea/fonts/Lidea.ttf

    - family: Mm3Web
      fonts:
        - asset: packages/lidea/fonts/Mm3Web.ttf
